import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { fontVariables } from "./font";
import { LocalDbProvider } from "@/providers/local-db-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/shadcn-ui/sonner";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontVariables}>
        <ThemeProvider>
          <LocalDbProvider>
            {children}
            <Toaster />
          </LocalDbProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
