import "./globals.css";
import type { Metadata } from "next";
import { fontVariables } from "./font";
import { LocalDbProvider } from "@/providers/local-db-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/shadcn-ui/sonner";
import { QueryProvider } from "@/providers/query-provider";

export const metadata: Metadata = {
  title: "Todo but SQL",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontVariables}>
        <QueryProvider>
          <ThemeProvider>
            <LocalDbProvider>
              {children}
              <Toaster />
            </LocalDbProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
