import "../globals.css";
import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { fontVariables } from "../font";
import { LocalDbProvider } from "@/providers/local-db-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/shadcn-ui/sonner";
import { QueryProvider } from "@/providers/query-provider";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
  title: "Todo but SQL",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={fontVariables}>
        <NextIntlClientProvider>
          <NuqsAdapter>
            <QueryProvider>
              <ThemeProvider>
                <LocalDbProvider>
                  {children}
                  <Toaster />
                </LocalDbProvider>
              </ThemeProvider>
            </QueryProvider>
          </NuqsAdapter>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
